# Name of the workflow
name: Release

# Runon every commit tag which begins with "v"
on:
  push:
    tags:
      -"v*"

# Automatically create a GitHub Release
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true