# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

# name: AutoRelease

# on:
#   push:
#     branches: [ main ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   release:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - uses: actions/checkout@v2
#       - uses: CupOfTea696/gh-action-auto-release@v1.0.2
#         with:
#           title: "Release: $version"
#           tag: "v*"
#           draft: false
#           regex: "/^Release: #{semver}$/i"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.0.1"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
